"""Load diagnostics: why a package was rejected, safe to log (no absolute paths, no content)."""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum


class DiagnosticCode(StrEnum):
    INVALID_DIRECTORY_NAME = "INVALID_DIRECTORY_NAME"
    SYMLINK_NOT_ALLOWED = "SYMLINK_NOT_ALLOWED"
    MISSING_FILE = "MISSING_FILE"
    NOT_A_REGULAR_FILE = "NOT_A_REGULAR_FILE"
    NOT_A_DIRECTORY = "NOT_A_DIRECTORY"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UNREADABLE_FILE = "UNREADABLE_FILE"
    INVALID_ENCODING = "INVALID_ENCODING"
    INVALID_TOML = "INVALID_TOML"
    INVALID_JSON = "INVALID_JSON"
    INVALID_JSON_ROOT = "INVALID_JSON_ROOT"
    UNSUPPORTED_SCHEMA_VERSION = "UNSUPPORTED_SCHEMA_VERSION"
    MISSING_PROPERTY = "MISSING_PROPERTY"
    UNKNOWN_FORM_PROPERTY = "UNKNOWN_FORM_PROPERTY"
    INVALID_PROPERTY = "INVALID_PROPERTY"
    INVALID_FORM_ID = "INVALID_FORM_ID"
    INVALID_SLUG = "INVALID_SLUG"
    INVALID_STATUS = "INVALID_STATUS"
    FORM_ID_MISMATCH = "FORM_ID_MISMATCH"
    DUPLICATE_FORM_ID = "DUPLICATE_FORM_ID"
    DUPLICATE_SLUG = "DUPLICATE_SLUG"
    # elements.toml
    INVALID_ELEMENTS_SCHEMA = "INVALID_ELEMENTS_SCHEMA"
    TOO_MANY_ELEMENTS = "TOO_MANY_ELEMENTS"
    INVALID_ELEMENT_ID = "INVALID_ELEMENT_ID"
    DUPLICATE_ELEMENT_ID = "DUPLICATE_ELEMENT_ID"
    UNKNOWN_ELEMENT_TYPE = "UNKNOWN_ELEMENT_TYPE"
    UNSUPPORTED_ELEMENT_TYPE = "UNSUPPORTED_ELEMENT_TYPE"
    UNKNOWN_ELEMENT_PROPERTY = "UNKNOWN_ELEMENT_PROPERTY"
    UNSUPPORTED_ELEMENT_PROPERTY = "UNSUPPORTED_ELEMENT_PROPERTY"
    MISSING_ELEMENT_PROPERTY = "MISSING_ELEMENT_PROPERTY"
    INVALID_ELEMENT_PROPERTY = "INVALID_ELEMENT_PROPERTY"
    INVALID_CONSTRAINT = "INVALID_CONSTRAINT"
    INVALID_OPTIONS = "INVALID_OPTIONS"
    DUPLICATE_OPTION_VALUE = "DUPLICATE_OPTION_VALUE"
    DUPLICATE_OPTION_LABEL = "DUPLICATE_OPTION_LABEL"
    INVALID_NORMALIZATION = "INVALID_NORMALIZATION"


@dataclass(frozen=True, slots=True)
class Diagnostic:
    relative_path: str
    file: str | None
    code: DiagnosticCode
    message: str


_SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9._-]{1,80}\Z")


def safe_name(name: str) -> str:
    """Directory or key names come from the filesystem; escape anything unusual before logging."""
    if _SAFE_NAME_RE.match(name):
        return name
    return ascii(name[:80])
